# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Not A Developer Talbot
email: talshoe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm trying to just learn some stuff and see what happens. And, I'm just trying out codecademy and github stuff. So what do I know. More about networking and web services clearly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://twistedsyx.net" # the base hostname & protocol for your site
twitter_username: nihilistikea
github_username:  towelbot

# Build settings
markdown: kramdown
